### ISSUE TITLE
Conversion of commandline flags

### ISSUE THREAD

**Issue by Stortebecker** [WorkflowConversion/CTD2Galaxy#17]
When a commandline flag is converted with CTD to a dropdown menu, the menu has three options: TRUE, FALSE and "Nothing selected". This is due to the entry `optional="True"`. However, for flags this is unwanted behaviour, as a missing flag normally means that the default is FALSE. So the option "Nothing selected" should not be there. A flag would be better reflected with `optional="False", value="False"`.

To be clear, my definition of "flag" is: a commandline parameter, which takes no additional input (T/F, String etc.). For example: adding `-append` to a command translates to `append=T`, with the default `append=F`. 

Sorry for the lengthy explanation, I am still new to this.I hope I made myself clear.

**Comment by Stortebecker** [comment]
@blankclemens I think that you solved this already, am I correct? Can we close this issue?

**Comment by chahuistle** [comment]
I am not sure how I could test this. Would anyone provide a CTD snippet and the desired ToolConfig snippet so I can test?

**Comment by blankclemens** [comment]
Fixed in 04d21efebbb0a8cdff01f70bd5123c99f2baf362 . If the default parameter is present in the select choices there is no need for "Nothing selected".
