### ISSUE TITLE
produces incomplete output tag

### ISSUE THREAD

**Issue by mwalzer** [WorkflowConversion/CTD2Galaxy#20]
The converter produces 
```
<outputs>
    <data name="param_out" format="data"/>
</outputs>
```
I think, there are two issues with that:
 * type is missing and should be 'data'
 * format is available in the ctd, but not included

What I presume would be better:
```
<outputs>
    <data name="param_out" type="data" format="idXML"/>
</outputs>
```
from what is available in the ctd:
```
<ITEM name="out" value="" type="output-file" description="Output file" required="true" advanced="false" supported_formats="*.idXML" />
```

**Comment by mwalzer** [comment]
actually, as galaxy has a lot of ms formats already listed in their file-types listing, but all in lowercase, a `.toLower()` might be good 
```
<outputs>
    <data name="param_out" type="data" format="idxml"/>
</outputs>
```

**Comment by bgruening** [comment]
@mwalzer the output does not have a type in Galaxy. The format should really be fixed. Once we discussed a file that maps the different filetype annotations or use EDAM for it.

**Comment by chahuistle** [comment]
It seems to me that the function `create_output_node` (line 1269 in `generator.py`) would be the one to modify. This is where `generator.py` tries to obtain the right value for the `format` attribute. I am just worried about the `type` attribute in `data` elements, as @bgruening commented.

**Comment by mwalzer** [comment]
Yes, @bgruening is right, according to the [galaxy doc](https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-outputs-data) no type attribute. It should then looke something like:
````
<outputs>
    <data name="param_out" format="idxml"/>
</outputs>
```

**Comment by chahuistle** [comment]
Right now, formats are kept as provided. A temporary work around would be to modify your CTDs so their format is "idxml" and not "idXML".

I guess an extra parameter can be added "make formats all upper-/lowercase", and depending on that, formats will be left alone (as it is now), uppercased or lowercased.

**Comment by mwalzer** [comment]
No, I think right now, by default, data is written as a format. Only if you supply a formats_file that contains this specific format, the type gets written (as mapped in the formats_file).

**Comment by chahuistle** [comment]
Can you provide an input file and the command line to replicate this on my end?

**Comment by chahuistle** [comment]
Well, anyway, missing output format, given that an input contains `supported_formats`, is a bug and this should be fixed.
