### ISSUE TITLE
UnicodeEncodeError for u'\xb2'

### ISSUE THREAD

**Issue by mwalzer** [WorkflowConversion/CTD2Galaxy#22]
There appears to be a parsing error in one of the OpenMS ctd files. Though I'm not sure where, file looks okay on a first glance. Can't find any u'\xb2' (² ?).  
[Offending file attached.](https://github.com/WorkflowConversion/CTD2Galaxy/files/986889/MetaProSIP.ctd.txt)

```
INFO: Converting from /tmp/ctd/MetaProSIP.ctd 
Traceback (most recent call last):
  File "generator.py", line 352, in main
    xsd_location=args.xsd_location)
  File "generator.py", line 598, in convert
    create_inputs(tool, model, **kwargs)
  File "generator.py", line 965, in create_inputs
    create_param_attribute_list(param_node, param, kwargs["supported_file_formats"])
  File "generator.py", line 1129, in create_param_attribute_list
    label, help_text = generate_label_and_help(param.description)
  File "generator.py", line 1139, in generate_label_and_help
    desc = str(desc).replace("#br#", " <br>")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb2' in position 9: ordinal not in range(128)
```

**Comment by chahuistle** [comment]
Seems to be in the description or manual of the file. The method `generate_label_and_help` takes the `<description>` and `<manual>` elements from the CTD. 

What happens if you clear those elements from the CTD and try again? Is the encoding of your input file UTF-8?

**Comment by mwalzer** [comment]
The same.
These are <![CDATA[...]]> elements, so they should not be interpreted by the xml parser

**Comment by mwalzer** [comment]
UTF-8, yes

**Comment by chahuistle** [comment]
Oh, on closer inspection, I now realize that this part of the code is responsible to generate description for parameters. The offending parameter could be `decomposition_threshold`, which has the following description: "Minimum R² of decomposition that must be achieved for a peptide to be reported."

**Comment by mwalzer** [comment]
Ah, yes. So ² should have ascii correspondence, but it's extended ascii (253).

**Comment by mwalzer** [comment]
Update: traced it down to ```generate_label_and_help``` but I think the problem might lie within value handling of lxml/CTDopts:
injecting a  ```print type(desc)``` at the start yields for a file with funny characters something like:
```
<type 'str'>
<type 'str'>
<type 'str'>
<type 'str'>
<type 'unicode'>
<type 'str'>
<type 'str'>
<type 'str'>
...
```
Where unicode contains the funny character, and this breaks [```str(desc)```](https://github.com/WorkflowConversion/CTD2Galaxy/blob/master/generator.py#L1136)

Taking apart the cast and handling encoded strings (assumed by default utf8 instead of ascii) should do the trick.
